// Generated by CoffeeScript 1.7.1
(function() {
  var request;

  request = require('superagent');

  window.onerror = function(e, url, l) {
    var data, server;
    data = {
      msg: e,
      file: url,
      line: l
    };
    server = "http://requestb.in/xcglyexc";
    return request.post(server).query(JSON.stringify(data)).end(function() {});
  };

}).call(this);
